version: 2.1
orbs:
  node: circleci/node@1.1.6
  heroku: circleci/heroku@1.0.1
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '10.10'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run lint
            - run: npm run test:unit
workflows:
  build-and-test:
    jobs:
      - build-and-test
  heroku-deploy:
    jobs:
      - build-and-test
      - heroku/deploy-via-git:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
