version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
      taf: '10.10'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run lint 
            - run: npm test:unit
workflows:
    build-and-test:
      jobs:
        - build-and-test